name: Pandoc example
on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Lorem ipsum" > lorem_1.md  # create two example files
          echo "dolor sit amet --- here's a new line" > lorem_2.md
          mkdir -p output  # create output dir
          # this will also include README.md
          echo "FILELIST=$(printf '"%s" ' *.md)" >> $GITHUB_ENV
      - run: sudo fc-cache -fv
      - uses: docker://pandoc/latex:2.9
        with:
          args: >-
            -o output/a-new-file.pdf
            --pdf-engine=xelatex
            --variable mainfont="Palatino"
            docs/make-sub-dir/a-new-file.md
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: output
      #- uses: mikeal/publish-to-github-action@master
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    BRANCH_NAME: 'main'
